-- MySQL Script generated by MySQL Workbench
-- sáb 25 jul 2020 16:00:42 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema devShop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema devShop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `devShop` DEFAULT CHARACTER SET utf8 ;
USE `devShop` ;

-- -----------------------------------------------------
-- Table `devShop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devShop`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(245) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devShop`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devShop`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devShop`.`product_variations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devShop`.`product_variations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(245) NULL,
  `available` INT NULL,
  `variation_name` VARCHAR(245) NULL,
  `price` FLOAT NULL,
  `price_from` FLOAT NULL,
  `weight` INT NULL,
  `order` INT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_variations_products_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_variations_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `devShop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devShop`.`product_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devShop`.`product_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(245) NULL,
  `url` VARCHAR(245) NULL,
  `order` INT NULL,
  `product_variation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_images_product_variations1_idx` (`product_variation_id` ASC),
  CONSTRAINT `fk_product_images_product_variations1`
    FOREIGN KEY (`product_variation_id`)
    REFERENCES `devShop`.`product_variations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devShop`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devShop`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(245) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devShop`.`categories_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devShop`.`categories_products` (
  `categorie_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`categorie_id`, `product_id`),
  INDEX `fk_categories_has_products_products1_idx` (`product_id` ASC),
  INDEX `fk_categories_has_products_categories1_idx` (`categorie_id` ASC),
  CONSTRAINT `fk_categories_has_products_categories1`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `devShop`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_has_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `devShop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devShop`.`banner_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devShop`.`banner_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `banner_type` VARCHAR(245) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devShop`.`banners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devShop`.`banners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(245) NULL,
  `banner_type_id` INT NOT NULL,
  `url` VARCHAR(245) NULL,
  `order` INT NULL,
  `image_url` VARCHAR(245) NULL,
  PRIMARY KEY (`id`, `banner_type_id`),
  INDEX `fk_banners_banner_types1_idx` (`banner_type_id` ASC),
  CONSTRAINT `fk_banners_banner_types1`
    FOREIGN KEY (`banner_type_id`)
    REFERENCES `devShop`.`banner_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
INSERT INTO `devShop`.`categories` (`id`, `category`, `description`) VALUES ('1', 'Eletronicos', 'Eletronicos');
INSERT INTO `devShop`.`categories` (`id`, `category`, `description`) VALUES ('2', 'Eletrodomesticos', 'Eletrodomesticos');
INSERT INTO `devShop`.`categories` (`id`, `category`, `description`) VALUES ('3', 'Celulares', 'Celulares');